K_Pro_Petstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('crud/', include('crud.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', root),
    path('home', home, name='home'),
    path('productos', productos, name='productos'),
    path('producto/<str:product_id>/', detalle_producto,name='product-detail'),
    path('contacto', contacto, name='contacto'),
    path('nosotros', nosotros, name="nosotros")
]

crud/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', product_list, name='product-list'),
    path('new/', product_new, name='product-new'),
    path('<str:product_id>/', product_detail, name='product-detail'),
    path('<str:product_id>/edit', product_edit, name='product-edit'),
    path('<str:product_id>/delete',product_delete,name='product-delete')
]

crud/models.py
from distutils.command.upload import upload
from hashlib import blake2b
from tabnanny import verbose
from django.db import models

# Create your models here.
class Marca(models.Model):
    marca = models.CharField(max_length=50, verbose_name='Marca')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'marca'
        verbose_name_plural = 'marcas'
        ordering = ['marca']

    def __str__(self):
        return self.marca

class Producto(models.Model):
    id_producto = models.CharField(primary_key=True,max_length=20, verbose_name='ID')
    nombre = models.CharField(max_length=50, verbose_name='Nombre')
    precio = models.IntegerField(verbose_name='Precio')
    stock = models.IntegerField(verbose_name='Stock')
    imagen = models.ImageField(verbose_name='Imagen', upload_to='productos',null=True, blank=True)
    descripcion = models.CharField(max_length=200, verbose_name='Descripción')
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='producto'
        verbose_name_plural='productos'
        ordering=['id_producto']

    def __str__(self):
        return self

crud/forms.py
from dataclasses import fields
from django import forms
from django.forms import ModelForm, widgets
from .models import *

class ProductForm(ModelForm):

    class Meta:
        model = Producto
        fields = [
            'id_producto',
            'nombre',
            'precio',
            'stock',
            'imagen',
            'descripcion',
            'marca'
        ]
        labels = {
            'id_producto':'Código Producto',
            'nombre':'Nombre Producto',
            'precio':'Precio',
            'stock':'Stock',
            'imagen':'Imagen',
            'descripcion':'Descripción',
            'marca':'Marca'
        }
        widgets = {
            'id_producto':forms.TextInput(attrs={'class':'form-control'}),
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'precio':forms.TextInput(attrs={'class':'form-control', 'type':'number'}),
            'stock':forms.TextInput(attrs={'class':'form-control', 'type':'number'}),
            'imagen':forms.FileInput(attrs={'class':'form-control custom-file-input', 'lang':'es'}),
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
            'marca':forms.Select(attrs={'class':'form-control'})
        }

crud/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpRequest
from .models import *
from .forms import *


# Create your views here.

def product_list(request):
    context = {'productos':Producto.objects.all()}
    return render(request, 'crud/product_list.html', context)

def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST,request.FILES)
        if form.is_valid():
            id_producto = form.cleaned_data.get("id_producto")
            nombre = form.cleaned_data.get("nombre")
            precio = form.cleaned_data.get("precio")
            stock = form.cleaned_data.get("stock")
            marca = form.cleaned_data.get("marca")
            imagen = form.cleaned_data.get("imagen")
            descripcion = form.cleaned_data.get("descripcion")
            obj = Producto.objects.create(
                id_producto=id_producto,
                nombre = nombre,
                precio=precio,
                stock=stock,
                imagen=imagen,
                descripcion=descripcion,
                marca=marca
            )
            obj.save()
            return redirect(reverse('product-new')+"?OK")
        else:
            return redirect(reverse('product-new')+"?FAIL")
    else:
        form = ProductForm
    return render(request,'crud/product_new.html',{'form':form})

def product_detail(request, product_id):
    try:
        producto = Producto.objects.get(id_producto=product_id)
        if producto:
            context = {'producto':producto}
            return render(request,'crud/product_detail.html',context)
    except:
        return redirect(reverse('product-list') + "?FAIL")


def product_edit(request, product_id):
    try:
        producto = Producto.objects.get(id_producto=product_id)
        if producto:
            form = ProductForm(instance=producto)
        else:
            return redirect(reverse('product-list') + "?FAIL")

        if request.method == 'POST':
            form = ProductForm(request.POST,request.FILES,instance=producto)
            if form.is_valid():
                form.save()
                return redirect(reverse('product-list') + "?SUCCESS")
            else:
                return redirect(reverse('product-edit') + product_id)
        context = {'form':form}
        return render(request,'crud/product_edit.html',context)
    except:
        return redirect(reverse('product-list') + "?FAIL")

def product_delete(request, product_id):
    try:
        producto = Producto.objects.get(id_producto=product_id)
        producto.delete()
        return redirect(reverse('product-list') + "?DELETED")
    except:
        return redirect(reverse('product-list') + "?FAIL")

crud/templates/crud/product_detail.html
{% extends 'crud/base.html' %}

{% load static %}
{% block tittle %}Lista de Productos{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
        <h2 class="col-12 p-2 text-primary">DETALLE PRODUCTO</h2>
    </div>
</div>

<div class="container mt-4 mb-4">
    <div class="row mb-3">
        <h3>Producto: {{producto.nombre}}</h3>
    </div>
    <div class="row">
        <div class="col-md-4">
            {% if producto.imagen %}
            <img class="img-thumbnail" src="{{producto.imagen.url}}" alt="{{producto.id_producto}}">
            {% else %}
            <img class="img-thumbnail" src="{% static 'crud/img/folder-x.svg' %}" alt="Not found">
            {% endif %}
            <div class="row mt-2 d-flex justify-content-center">
                <a class="btn btn-outline-dark mx-1" href="{% url 'product-edit' producto.id_producto  %}">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a class="btn btn-outline-danger mx-1 modal-borrar" data-toggle="modal" data-bs-toggle="modal" data-target="#staticBackdrop" data-bs-target="#staticBackdrop" data-href="{% url 'product-delete' producto.id_producto  %}">
                    <i class="bi bi-trash3"></i>
                </a>
            </div>
        </div>
        <div class="col-md-8 ps-1">
            <ul class="list-unstyled">
            </li>
                <li class="mb-2">ID: <p class="font-weight-bold">{{producto.id_producto}}</p>
                <li class="mb-2">Marca: <p class="font-weight-bold">{{producto.marca}}</p>
                </li>
                <li class="mb-2">Precio: <p class="font-weight-bold">${{producto.precio}}</p></li>
                <li class="mb-2">Stock: <p class="font-weight-bold">{{producto.stock}}</p></li>
                <li class="mb-2">Descripción: <p class="font-weight-bold">{{producto.descripcion}}</p>
                <li class="mb-2">Registrado: <p class="text-muted fst-italic font-weight-bold">{{producto.created_at | date:'d-m-Y'}}</p></li>
                <li class="mb-2">Última actulización: <p class="text-muted fst-italic font-weight-bold">{{producto.updated_at | date:'F d, Y H:m'}}</p></li>
            </ul>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">ALERTA</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro que quieres eliminar el producto?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                <a id="confirmar-borrar" class="btn btn-success" href="#">Eliminar</a>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'crud/js/modal.js' %}"></script>

{% endblock %}

crud/templates/crud/product_edit.html
{% extends 'crud/base.html' %}

{% load static %}
{% block tittle %}Actualizar Productos{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
        <h5 class="col-12 p-2 text-primary">EDITAR PRODUCTO</h5>
    </div>
</div>

<div class="container mb-4">

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_producto" class="font-weight-bold">Código Producto</label>
            <div class="input-group">
                {{form.id_producto}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="nombre" class="font-weight-bold">Nombre</label>
            <div class="input-group">
                {{form.nombre}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="precio" class="font-weight-bold">Precio</label>
            <div class="input-group">
                {{form.precio}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="stock" class="font-weight-bold">Stock</label>
            <div class="input-group">
                {{form.stock}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="descripcion" class="font-weight-bold">Descripción</label>
            <div class="input-group">
                {{form.descripcion}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="marca" class="font-weight-bold">Marca</label>
            <div class="input-group">
                {{form.marca}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="imagen" class="font-weight-bold">Imagen</label>
            <div class="input-group custom-file">
                {{form.imagen}}
                <label class="custom-file-label" for="id_imagen">Elige el Archivo</label>
            </div>
            {% if form.instance.imagen %}
                <div class="div">
                    <img class="img-update" src="{{form.instance.imagen.url}}" alt="">
                </div>
            {% endif %}
        </div>
        <div class="text-center mt-4">
            <input type="submit" class="btn btn-outline-primary btn-block py-2" id="actualizar" value="Actualizar">
            <input type="reset" class="btn btn-outline-success btn-block py-2" id="limpiar" value="Limpiar">
        </div>
    </form>
</div>


<script src="{% static 'crud/js/main.js' %}"></script>
{% endblock %}

crud/templates/crud/product_list.html
{% extends 'crud/base.html' %}

{% load static %}
{% block tittle %}Lista de Productos{% endblock %}

{% block content %}


<div class="container text-center">
    <div class="row">
        <h5 class="col-12 p-2 text-primary">LISTA DE PRODUCTOS</h5>
    </div>
</div>

<div class="container-fluid mt-4 mb-4">

    {% if 'SUCCESS' in request.GET %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Acción realizada!
    </div>
    {% endif %}
    {% if 'DELETED' in request.GET %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Producto eliminado!
    </div>
    {% endif %}
    {% if 'FAIL' in request.GET %}
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Error al agregar al realizar la acción!
    </div>
    {% endif %}

    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover ">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Nombre</td>
                        <td>Precio</td>
                        <td>Stock</td>
                        <td>Imagen</td>
                        <td>Descripción</td>
                        <td>Marca</td>
                        <td>Opciones</td>
                    </tr>
                </thead>
                <tbody>
                    {% for p in productos %}
                    <tr>
                        <td>
                            <a href="/crud/{{p.id_producto}}">{{p.id_producto}}</a>
                        </td>
                        <td>{{p.nombre}}</td>
                        <td>{{p.precio}}</td>
                        <td>{{p.stock}}</td>
                        {% if p.imagen %}
                        <td><img class="img-producto" src="{{p.imagen.url}}" alt="{{p.id_producto}}"></td>
                        {% else %}
                        <td><img class="img-producto" src="{% static 'crud/img/folder-x.svg' %}" alt="{{p.id_producto}}">
                        </td>
                        {% endif %}
                        <td>{{p.descripcion}}</td>
                        <td>{{p.marca}}</td>
                        <td>
                            <a class="btn btn-outline-dark mb-1" href="/crud/{{p.id_producto}}">
                                <i class="bi bi-eye-fill"></i>
                            </a>
                            <a class="btn btn-outline-dark mb-1" href="/crud/{{p.id_producto}}/edit">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a class="btn btn-outline-danger mb-1 modal-borrar" data-toggle="modal" data-bs-toggle="modal" data-target="#staticBackdrop" data-bs-target="#staticBackdrop" data-href="{% url 'product-delete' p.id_producto %}">
                                <i class="bi bi-trash3"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">ALERTA</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
            <div class="modal-body">
                ¿Estás seguro que quieres eliminar el producto?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                <a id="confirmar-borrar" class="btn btn-success" href="#">Eliminar</a>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'crud/js/modal.js' %}"></script>

{% endblock %}

crud/templates/crud/product_new.html
{% extends 'crud/base.html' %}

{% load static %}
{% block tittle %}Lista de Productos{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
        <h5 class="col-12 p-2 text-primary">AÑADIR PRODUCTO</h5>
    </div>
</div>

<div class="container mt-4 mb-4">

    {% if 'OK' in request.GET %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Producto Agregado Correctamente!
    </div>
    {% endif %}
    {% if 'FAIL' in request.GET %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Error al agregar el producto!
    </div>
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="id_producto" class="font-weight-bold">Código Producto</label>
            <div class="input-group">
                {{form.id_producto}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="nombre" class="font-weight-bold">Nombre</label>
            <div class="input-group">
                {{form.nombre}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="precio" class="font-weight-bold">Precio</label>
            <div class="input-group">
                {{form.precio}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="stock" class="font-weight-bold">Stock</label>
            <div class="input-group">
                {{form.stock}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="imagen" class="font-weight-bold">Imagen</label>
            <div class="input-group custom-file">
                {{form.imagen}}
                <label class="custom-file-label" for="id_imagen">Elige el Archivo</label>
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="descripcion" class="font-weight-bold">Descripción</label>
            <div class="input-group">
                {{form.descripcion}}
            </div>
        </div>
        <div class="form-group mb-3">
            <label for="marca" class="font-weight-bold">Marca</label>
            <div class="input-group">
                {{form.marca}}
            </div>
        </div>
        <div class="text-center mt-4">
            <input type="submit" class="btn btn-outline-primary btn-block py-2" id="enviar" value="Registrar">
            <input type="reset" class="btn btn-outline-success btn-block py-2" id="limpiar" value="Limpiar">
        </div>
    </form>
</div>

<script src="{% static 'crud/js/main.js' %}"></script>
{% endblock %}